### ISSUE TITLE
what is the purpose to use thumbulator?

### ISSUE THREAD

**Issue by wenij** [ekoeppen/CoreForth#3]
because I see , thumb-2 instruction not implemented. and don't known what will happen....

==
thumbulator -d coreforth.bin -m 00010000 -d ../generic/systick.ft -d ../generic/quit.ft -d stm32f103.ft -o coreforth.bin.1
Stored file coreforth.bin (262144 bytes) at address 0x00000000
Stored file ../generic/systick.ft (270 bytes) at address 0x00010000
Stored file ../generic/quit.ft (334 bytes) at address 0x0001010e
Stored file stm32f103.ft (12918 bytes) at address 0x0001025c
Thumb-2 instruction 0xf04f 4160 at 0x080002be not implemented
===

wenij

**Comment by ekoeppen** [comment]
Thumbulator only supports the minimum instructions needed to bootstrap the system and start executing Forth code. For which target did you try to compile?

**Comment by larsbrinkhoff** [comment]
Hello,

Kind of related to this.. I see you are using both thumbulator, and QEMU.  Why is that?

I'm looking for a simulator primarily for Cortex-M0 devices.  I'd like to use it for automated test, so it's crucial that the simulator can be halted from within the simulation.  Thumbulator quits when it encounters a BKPT instruction, but QEMU doesn't seem to have this feature.  Does that seem correct to you?

**Comment by ekoeppen** [comment]
I modified thumbulator just for enabling precompilation, the quit on bkpt is specific to a dedicated bkpt trap. I think you can easily modify it if needed.

**Comment by larsbrinkhoff** [comment]
Thanks, I'm using your version of thumbulator.

**Comment by ekoeppen** [comment]
I updated thumbulator now to also handle the opcode above, I was using that in CoreForth SE for Cortex M3 targets
